### ISSUE TITLE
Number mask for negative values

### ISSUE THREAD

**Issue by vanglian** [paulhodel/jsuites#14]
I was able to use number mask for positive values. But for negative values, it removes the negative sign. The mask works perfectly. Is there a way to retain the negative sign? I am using the mask in Jexcel CE (Jexcel V3).

**Comment by paulhodel** [comment]
This has been fixed. Use

[-]$ #.##,00 for example

**Comment by Qebbo** [comment]
it seems that the [-] option introduced a new problem: the first character that you enter in a masked field with a masked that starts with [-] disappears in thin air. You can reproduce on the example on the jsuites site itself: https://bossanova.uk/jsuites/javascript-mask

just type 21 in the currency example and it will only show U$ 1  (instead of 21)

**Comment by paulhodel** [comment]
Agree that should be improved. I am working on it.

**Comment by paulhodel** [comment]
It has been fixed in the master repository and the website.
